# Chat de Calais : le pipeline RAG pas à pas

## Avant de commencer

« Chat de Calais » est un assistant qui répond à des questions sur les notes et courriers préparés par la DDTM pour les réunions bilatérales avec le préfet en 2024. Il repose sur le principe du RAG (Retrieval-Augmented Generation) : plutôt que de laisser un modèle de langage répondre de mémoire, on commence par retrouver dans les documents les passages utiles, puis on demande au modèle de rédiger une réponse fondée sur eux et de citer ses sources.

Ce notebook déroule la chaîne complète, de la lecture des fichiers à la génération de la réponse. Chaque section expose le rôle d'une étape, la raison de sa présence, puis la manière de lire la sortie de la cellule de code qui la suit. Les agents y trouveront une présentation du fonctionnement de l'outil, les développeurs un repérage des modules concernés.

Trois prérequis conditionnent l'exécution. La clé d'API Albert doit figurer dans le fichier `.env`. La base doit avoir été indexée au préalable avec la commande `python main.py`. Enfin, le notebook se lance depuis la racine du projet ou depuis le dossier du notebook, afin que les chemins relatifs soient résolus correctement. Certaines cellules interrogent l'API et peuvent donc prendre quelques secondes.

In [1]:
# Préparation : se placer à la racine du projet, journal discret
import os, sys
from pathlib import Path

ROOT = Path.cwd() if (Path.cwd() / "config.py").exists() else Path.cwd().parent
os.chdir(ROOT)
sys.path.insert(0, str(ROOT))

import config
config.VERBOSE = False
config.setup_logging()

import polars as pl
import altair as alt
from IPython.display import Markdown, display

print("Base vectorielle :", config.CHROMA_DB_PATH)
print("Modèle de réponse :", config.LLM_MODEL, "| embeddings :", config.EMBEDDINGS_MODEL,
      "| rerank :", config.RERANK_MODEL, "| OCR :", config.OCR_MODELS[config.OCR_ENGINE])

Base vectorielle : _tmp/chroma_full
Modèle de réponse : openweight-medium | embeddings : openweight-embeddings | rerank : openweight-rerank | OCR : openweight-ocr

## 1. Paramètres

L'ensemble des réglages de l'application est regroupé dans le fichier `parametres.yaml`. Il couvre les modèles Albert, la recherche, le découpage des textes, l'OCR, l'interface et les prompts. Chaque clé y est commentée, de sorte qu'une personne qui ne développe pas puisse modifier une valeur sans lire le code. Le module `config.py` lit ce fichier, en valide le contenu et expose des constantes au reste du programme. En cas d'erreur, le message est rédigé en français et désigne la clé fautive. La clé d'API reste dans `.env`, qui peut aussi surcharger quelques réglages.

Les valeurs retenues ici sont les suivantes : 30 candidats par méthode de recherche, 5 passages conservés au final, HyDE désactivé, recherche hybride et rerank activés, score minimum de 0,03, un voisin de chaque côté, dédoublonnage actif avec au plus 2 passages par document, passages de 2 000 caractères avec 400 de chevauchement et en-tête contextuel activé. Les modèles sont appelés via l'API Albert (Etalab) : openweight-medium pour la réponse, openweight-embeddings pour les vecteurs, openweight-rerank pour le classement et openweight-ocr, alias de lightonocr-2-1b, pour les pages scannées.

La cellule suivante affiche ces valeurs telles que le programme les voit.

In [2]:
# Les réglages de la recherche, lus dans parametres.yaml
pl.DataFrame({
    "réglage (parametres.yaml)": ["recherche.candidats_par_methode", "recherche.passages_retenus",
                                  "recherche.hyde", "recherche.hybride", "recherche.rerank",
                                  "recherche.score_minimum", "recherche.voisins",
                                  "recherche.dedoublonnage", "recherche.max_passages_par_document",
                                  "decoupage.taille", "decoupage.entete_contextuel"],
    "valeur": [str(v) for v in (config.RETRIEVER_TOP_K, config.RAG_TOP_K_DOCS, config.USE_HYDE,
                                config.USE_HYBRID_SEARCH, config.USE_RERANK, config.RERANK_MIN_SCORE,
                                config.CONTEXT_NEIGHBORS, config.DEDUP_ENABLED,
                                config.MAX_PASSAGES_PER_DOCUMENT, config.CHUNK_SIZE, config.CONTEXT_HEADER)],
})

shape: (11, 2)
┌─────────────────────────────────┬────────┐
│ réglage (parametres.yaml)       ┆ valeur │
│ ---                             ┆ ---    │
│ str                             ┆ str    │
╞═════════════════════════════════╪════════╡
│ recherche.candidats_par_method… ┆ 30     │
│ recherche.passages_retenus      ┆ 5      │
│ recherche.hyde                  ┆ False  │
│ recherche.hybride               ┆ True   │
│ recherche.rerank                ┆ True   │
│ …                               ┆ …      │
│ recherche.voisins               ┆ 1      │
│ recherche.dedoublonnage         ┆ True   │
│ recherche.max_passages_par_doc… ┆ 2      │
│ decoupage.taille                ┆ 2000   │
│ decoupage.entete_contextuel     ┆ True   │
└─────────────────────────────────┴────────┘

## 2. Chargement des documents

Le corpus rassemble des notes et courriers rangés par dossier de réunion, nommé selon le format « jj mm aaaa » (par exemple « 08 04 2024 »). Un même dossier contient des brouillons, souvent au format ODT, et des versions « validée », « finale » ou « définitive », souvent en PDF. Une même note revient d'une réunion à l'autre. Au total, 130 fichiers sont concernés (PDF, ODT, DOCX, DOC, EML et images).

Chaque fichier est lu selon son format, et un PDF produit un document par page. Le chemin du fichier fournit en outre des métadonnées précieuses : la date de réunion, tirée du nom du dossier, le statut validé (les mots « validée », « finale », « définitive » ou « signée » figurant dans le chemin), le titre, et une « famille ». Cette dernière prend la même valeur pour toutes les versions et tous les formats d'une note, une fois retirés le numéro d'ordre, les dates et les marqueurs de type V2.

La sortie montre la note « Note Préfet PN -20240404 » en ODT (brouillon) puis en PDF, suivie du début du texte du PDF validé. Ce dernier compte trois pages et présente un plan d'actions pour la sécurisation des passages à niveau. On y vérifie que le texte est lisible et que les métadonnées sont cohérentes.

In [3]:
import glob
import corpus
from loaders import load_document

# Une note existe en brouillon (ODT) et en version validée (PDF)
chemins = sorted(glob.glob("documents/**/*Note Préfet PN*", recursive=True))
pl.DataFrame([{"fichier": Path(c).name, "dossier": Path(c).parent.name,
               **corpus.document_metadata(c)} for c in chemins])

shape: (3, 6)
┌──────────────────┬─────────────────┬──────────────┬───────────┬─────────────────┬────────────────┐
│ fichier          ┆ dossier         ┆ meeting_date ┆ validated ┆ doc_title       ┆ doc_family     │
│ ---              ┆ ---             ┆ ---          ┆ ---       ┆ ---             ┆ ---            │
│ str              ┆ str             ┆ i64          ┆ bool      ┆ str             ┆ str            │
╞══════════════════╪═════════════════╪══════════════╪═══════════╪═════════════════╪════════════════╡
│ Note Préfet PN   ┆ 08 04 2024      ┆ 20240408     ┆ false     ┆ Note Préfet PN  ┆ note prefet pn │
│ -20240404.odt    ┆                 ┆              ┆           ┆ -20240404       ┆                │
│ Note Préfet PN   ┆ 08 04 2024      ┆ 20240408     ┆ false     ┆ Note Préfet PN  ┆ note prefet pn │
│ -20240404.pdf    ┆                 ┆              ┆           ┆ -20240404       ┆                │
│ 5- Note Préfet   ┆ version validée ┆ 20240408     ┆ true      ┆ Note Préfet PN  ┆ note prefet pn │
│ PN -20240404.pd… ┆                 ┆              ┆           ┆ -20240404       ┆                │
└──────────────────┴─────────────────┴──────────────┴───────────┴─────────────────┴────────────────┘

In [4]:
pdf = [c for c in chemins if c.endswith(".pdf") and "valid" in c][0]
pages = load_document(pdf)
print(f"{Path(pdf).name} : {len(pages)} page(s)")
print(pages[0].page_content[:700])

5- Note Préfet PN -20240404.pdf : 3 page(s)
Direction départementale
des territoires et de la mer
Service Sécurité Éducation Routière Bâtiment et Crises
Unité Sécurité Routière et Gestion de Crises
Affaire suivie par : Raymond BEUDAERT
Tél : 03 21 22 91 04
Mél : raymond.beudaert@pas-de-calais.gouv.fr
Arras, le 4 avril 2024
Note à l’attention de Monsieur le Préfet
OBJET : Plan d’actions pour la sécurisation des passages à niveau
Point de situation au 16 février 2024
Conformément aux directives énoncées lors de la Commission Départementale de Suivi de la
Sécurisation des Passages à Niveau (CDSSPN), la DDTM recense les actions engagées par les
gestionnaires des routes et des infrastructures ferroviaires.
Pour ce qui concerne le point d’a

## 3. Reconnaissance de caractères (OCR)

Certains PDF sont des scans, c'est-à-dire des images de pages sans texte exploitable. Une page dont la couche texte compte moins de 50 caractères est donc considérée comme scannée. Elle est rendue en image (pypdfium2, 200 dpi) puis transcrite par le modèle OCR d'Albert. Les images insérées dans une page de texte, comme un schéma ou un tableau scanné, sont également lues lorsqu'elles couvrent entre 10 et 85 % de la page. Les résultats sont conservés dans un cache sur disque, ce qui évite de payer l'OCR à chaque exécution.

Le texte brut renvoyé par le modèle demande un nettoyage. Les tableaux HTML qu'il produit sont convertis en tableaux Markdown. Les boucles de répétition sont supprimées : une carte avait ainsi fait répéter « - CCA » 3 477 fois. La consigne que le modèle recopie parfois dans sa réponse est également retirée.

La cellule affiche une page OCR de la note « Point Parc privé Anah », rendue en Markdown. Elle contient le tableau des pactes territoriaux par EPCI. Il convient de comparer ce rendu à la page d'origine, car la qualité de l'OCR varie selon les documents.

In [5]:
# Une page lue par OCR (tableau inséré en image dans une note PDF), relue depuis le cache
anah = glob.glob("documents/**/*Parc privé Anah*.pdf", recursive=True)[0]
pages_anah = load_document(anah)
page_ocr = next(p for p in pages_anah if p.metadata.get("ocr") or p.metadata.get("ocr_images"))
print("Page", page_ocr.metadata["page"] + 1, "| OCR page entière :", page_ocr.metadata["ocr"],
      "| images lues :", page_ocr.metadata.get("ocr_images", 0))
display(Markdown(page_ocr.page_content[:1500]))

Page 1 | OCR page entière : True | images lues : 0

# PRÉFET DU PAS-DE-CALAIS

Liberté Égalité Fraternité

---

**Direction départementale des territoires et de la mer**

---

Service Habitat Renouvellement Urbain
Affaire suivie par : Séverine MERCIER
Tél : 03.21.22.99.39
Mél : severine.mercier@pas-de-calais.gouv.fr

Arras, le
08 OCT. 2024

---

## Note à l'attention de Monsieur le Préfet

### Objet : Point de situation Parc Privé/Anah au 30 septembre 2024

#### I/ Situation de la réalisation des objectifs

L'année 2024 représente une année de forte augmentation des aides allouées par l'Anah de part l'évolution de ses dispositifs MaPrimeRénov' Parcours Accompagné (rénovation énergétique d'ampleur), MaPrimeAdapt' (adaptation du logement au vieillissement et/ou au handicap) et MaPrimeLogement Décent (lutte contre l'habitat indigne) dont les montants de référence d'aide ont presque doublé à compter du 1er janvier 2024.

Ces nouvelles modalités de financement, bien que conditionnées par de nouvelles exigences en matière de gain énergétique pour le dispositif MaPrimeLogement Parcours Accompagné ont un effet incitatif et par conséquent une augmentation du nombre de dossiers déposés et financés. Même si au 30 septembre le nombre de dossiers engagés semble encore éloigné des objectifs 2024 à atteindre, le nombre de dossiers déposés en attente d'instruction est important, notamment chez les délégataires pour lesquels le paramétrage de la nouvelle réglementation dans l'outil d'instruction a été mis en place très tardivement.

L'

## 4. Découpage en passages

Un modèle de recherche travaille mal sur des pages entières. On découpe donc chaque document en passages d'environ 2 000 caractères, avec un chevauchement de 400 caractères afin qu'une phrase située à la frontière de deux passages ne soit pas coupée de son contexte. Chaque passage reçoit un numéro d'ordre dans son fichier, le `chunk_index`.

Un en-tête contextuel est placé devant le texte de chaque passage, par exemple « [Note Préfet PN -20240404 | réunion du 08/04/2024 | version validée] ». Il répond à une difficulté propre à ce corpus : des passages presque identiques proviennent de versions différentes d'une même note, et sans cet en-tête la recherche ne disposerait d'aucun indice pour les distinguer. Il est retiré à l'affichage pour ne pas encombrer la lecture.

La sortie présente le découpage de la note PN, qui donne 4 passages. On peut y observer le chevauchement entre deux passages consécutifs, ainsi que l'en-tête qui précède chacun d'eux. Au niveau du corpus complet, 855 passages sont indexés, dont 199 issus de l'OCR.

In [6]:
from indexer import split_documents

passages = split_documents(pages)
print(len(passages), "passages")
premier = passages[0]
print("En-tête contextuel :", premier.page_content[: premier.metadata["header_len"]])
print("Métadonnées :", {k: premier.metadata[k] for k in
      ("chunk_index", "meeting_date", "validated", "doc_title", "doc_family", "header_len")})

4 passages
En-tête contextuel : [Note Préfet PN -20240404 | réunion du 08/04/2024 | version validée]

Métadonnées : {'chunk_index': 0, 'meeting_date': 20240408, 'validated': True, 'doc_title': 'Note Préfet PN -20240404', 'doc_family': 'note prefet pn', 'header_len': 69}

## 5. Construction des index

Les mêmes passages alimentent deux index complémentaires. Le premier est une base vectorielle, Chroma, qui associe à chaque passage un vecteur numérique calculé par le modèle d'embeddings. Elle permet une recherche par le sens : deux formulations différentes d'une même idée aboutissent à des vecteurs proches. Le second est un index BM25 tenu en mémoire, qui recherche les mots exacts. Les mots vides et les accents y sont retirés, tandis que les nombres sont conservés, ce qui importe pour retrouver un montant ou une référence réglementaire.

Cette double indexation se justifie par la faiblesse respective de chaque approche. La recherche par le sens manque parfois une référence précise, la recherche par mots exacts ignore les synonymes. Les deux seront combinées plus loin.

Le graphique altair de la cellule montre le nombre de passages indexés par réunion et par statut (validé ou brouillon). Il permet de vérifier que chaque réunion est bien représentée et de mesurer le poids relatif des brouillons dans la base.

In [7]:
import chromadb
from chromadb.config import Settings
from langchain_chroma import Chroma
from albert_client import get_embeddings, get_llm
from retrieval import make_retriever

client = chromadb.PersistentClient(path=config.CHROMA_DB_PATH, settings=Settings(anonymized_telemetry=False))
store = Chroma(client=client, collection_name=config.COLLECTION_NAME, embedding_function=get_embeddings())
retriever = make_retriever(store)
llm = get_llm()

meta = pl.DataFrame([d.metadata for d in retriever.bm25_index.docs]).with_columns(
    pl.col("meeting_date").cast(pl.Utf8).str.strptime(pl.Date, "%Y%m%d", strict=False).alias("réunion"))
print(meta.height, "passages,", meta["source"].n_unique(), "fichiers,",
      meta.filter(pl.col("ocr") == True).height, "passages issus de l'OCR")
par_reunion = (meta.group_by("réunion", "validated").len().rename({"len": "passages"})
               .with_columns(pl.when(pl.col("validated")).then(pl.lit("version validée"))
                             .otherwise(pl.lit("version de travail")).alias("statut")))
alt.Chart(par_reunion.drop_nulls("réunion")).mark_bar().encode(
    x=alt.X("réunion:T", title="Réunion"), y=alt.Y("passages:Q", title="Passages indexés"),
    color=alt.Color("statut:N", title=None), tooltip=["réunion:T", "statut:N", "passages:Q"],
).properties(width=600, height=220, title="Passages indexés par réunion et par statut")

855 passages, 130 fichiers, 199 passages issus de l'OCR

alt.Chart(...)

## 6. Reformulation de la question

Dans une conversation, les questions de suivi sont souvent elliptiques. « Et quel est le calendrier ? » n'a aucun sens pour un moteur de recherche qui ne connaît pas l'échange précédent. Avant toute recherche, la question est donc réécrite sous une forme autonome par le modèle, à partir des trois derniers échanges.

La sortie de la cellule illustre deux cas. Dans le premier, « Et quel est le calendrier ? » devient « Quel est le calendrier de mise en œuvre des zones d'accélération des énergies renouvelables ? », le sujet ayant été repris de l'échange précédent. Dans le second, « Combien a coûté la capitainerie de Calais ? » change de sujet par rapport à l'historique et la question est conservée telle quelle. Ce second résultat est important : une reformulation qui injecterait à tort l'ancien sujet dégraderait la recherche.

Le prompt de reformulation se règle dans `parametres.yaml`.

In [8]:
from rag_pipeline import condense_question

historique = [
    {"role": "user", "content": "Où en sont les zones d'accélération des énergies renouvelables ?"},
    {"role": "assistant", "content": "La cartographie départementale a été arrêtée après la conférence territoriale [1]."},
]
for suivi in ["Et quel est le calendrier ?", "Combien a coûté la capitainerie de Calais ?"]:
    print(f"{suivi!r:50} -> {condense_question(suivi, historique, llm)!r}")

'Et quel est le calendrier ?'                      -> "Quel est le calendrier des zones d'accélération des énergies renouvelables ?"

'Combien a coûté la capitainerie de Calais ?'      -> 'Combien a coûté la capitainerie de Calais ?'

## 7. Réponse hypothétique (HyDE)

Une question et la réponse qui lui correspond ne s'expriment pas avec les mêmes mots. La méthode HyDE (Hypothetical Document Embeddings) tire parti de cet écart : le modèle rédige d'abord une réponse hypothétique, sans consulter les documents, et c'est ce texte qui sert à la recherche par le sens. Rédigé comme un passage de note administrative, il se situe plus près des documents du corpus que la question elle-même.

La sortie montre une telle réponse. Elle contient des références inventées, du type « loi n° 2023-XXX ». Cela reste sans conséquence, car ce texte ne sert qu'à chercher et n'est jamais utilisé pour répondre.

HyDE est pourtant désactivé par défaut depuis l'évaluation (section 13). Sur le jeu de questions, avec la recherche hybride, il n'apporte aucun gain mesurable : le taux de succès est identique et le MRR passe de 0,97 à 0,98. En contrepartie, il ajoute environ 15 s d'attente par question, contre 0,4 s sans lui. Il aide en revanche la recherche par le sens utilisée seule. La cellule l'active temporairement afin de présenter la démonstration, sans modifier `parametres.yaml`. La réponse hypothétique n'étant pas déterministe, deux exécutions peuvent produire des textes différents.

In [9]:
from rag_pipeline import generate_hyde

# HyDE est désactivé par défaut (recherche.hyde: false, voir l'évaluation) :
# on l'active ici le temps de la démonstration
config.USE_HYDE = True
question = "Quel est le calendrier de la conférence territoriale prévue par la loi APER ?"
requete_hyde = generate_hyde(question, llm)
config.USE_HYDE = False
print(requete_hyde[:900], "...")

Quel est le calendrier de la conférence territoriale prévue par la loi APER ?

**RÉPUBLIQUE FRANÇAISE**
**Ministère de l'Intérieur et des Collectivités Territoriales**
**Direction Générale des Collectivités Locales (DGCL)**

**Document de référence**
**Objet : Calendrier de la conférence territoriale prévue par la loi APER**

**Référence :** DGCL/2024/XXX
**Date :** [Date de publication]
**Destinataires :** Préfectures, collectivités territoriales, établissements publics de coopération intercommunale (EPCI), associations d'élus

---

### **1. Contexte réglementaire**
La **loi n°2023-XXX du [date] relative à l’accélération des projets économiques et de rationalisation (loi APER)** instaure une **conférence territoriale** visant à renforcer le dialogue entre l’État et les collectivités territoriales sur les politiques publiques locales. Cette conférence s’inscrit dans le cadre des disposit ...

## 8. Recherche hybride

La recherche vectorielle utilise la requête HyDE, tandis que BM25 reçoit la question d'origine, avec ses mots exacts. Chaque méthode produit son propre classement, à raison de 30 candidats. Ces deux classements sont ensuite fusionnés par Reciprocal Rank Fusion (RRF), qui attribue à chaque candidat un score fondé sur ses rangs dans les deux listes, avec une constante k égale à 60.

L'exemple de la cellule porte sur une référence exacte : la « référence NOR de l'instruction interministérielle du 1er juillet 2024 relative au Plan Eau ». La recherche vectorielle seule ne trouve aucun document pertinent dans ses cinq premiers résultats. BM25, en revanche, retrouve les notes Plan Eau ainsi que l'instruction elle-même. La fusion hybride fait remonter ces documents, sans pour autant les placer tous en tête.

Ce dernier point est attendu. La fusion produit un ensemble de bons candidats, et c'est le rerank, à l'étape suivante, qui effectuera le tri final.

In [10]:
def apercu(docs, n=5):
    """Tableau court des premiers documents trouvés."""
    return pl.DataFrame([{"rang": i + 1, "fichier": Path(d.metadata["source"]).name[:55],
                          "réunion": corpus.format_meeting_date(d.metadata.get("meeting_date"))}
                         for i, d in enumerate(docs[:n])])

q_ref = "Quelle est la référence NOR de l'instruction interministérielle du 1er juillet 2024 relative au Plan Eau ?"
print("Vectoriel seul"); display(apercu(retriever.vector_retriever.invoke(q_ref)))
print("BM25 seul");      display(apercu(retriever.bm25_index.search(q_ref, 30)))
print("Hybride (RRF)");  display(apercu(retriever.invoke(q_ref)))

Vectoriel seul

shape: (5, 3)
┌──────┬─────────────────────────────────┬────────────┐
│ rang ┆ fichier                         ┆ réunion    │
│ ---  ┆ ---                             ┆ ---        │
│ i64  ┆ str                             ┆ str        │
╞══════╪═════════════════════════════════╪════════════╡
│ 1    ┆ comite stratégique annexe form… ┆ 24/06/2024 │
│ 2    ┆ Note préfet Renouvellement LL.… ┆ 18/11/2024 │
│ 3    ┆ 3- Note préfet Renouvellement … ┆ 18/11/2024 │
│ 4    ┆ 2024-Note prefet loi inductrie… ┆ 14/10/2024 │
│ 5    ┆ 5-  laridés-20240905_V3 PMBG-1… ┆ 09/09/2024 │
└──────┴─────────────────────────────────┴────────────┘

BM25 seul

shape: (5, 3)
┌──────┬─────────────────────────────────┬────────────┐
│ rang ┆ fichier                         ┆ réunion    │
│ ---  ┆ ---                             ┆ ---        │
│ i64  ┆ str                             ┆ str        │
╞══════╪═════════════════════════════════╪════════════╡
│ 1    ┆ 4- Plan-Eau V2.odt              ┆ 09/09/2024 │
│ 2    ┆ 4- Plan-Eau V2.pdf              ┆ 09/09/2024 │
│ 3    ┆ 4- Note-Préfet_Déclinaison-dép… ┆ 09/09/2024 │
│ 4    ┆ 4 - Instruction datée et signé… ┆ 09/09/2024 │
│ 5    ┆ 4 - Instruction datée et signé… ┆ 09/09/2024 │
└──────┴─────────────────────────────────┴────────────┘

Hybride (RRF)

shape: (5, 3)
┌──────┬─────────────────────────────────┬────────────┐
│ rang ┆ fichier                         ┆ réunion    │
│ ---  ┆ ---                             ┆ ---        │
│ i64  ┆ str                             ┆ str        │
╞══════╪═════════════════════════════════╪════════════╡
│ 1    ┆ comite stratégique annexe form… ┆ 24/06/2024 │
│ 2    ┆ 4- Plan-Eau V2.odt              ┆ 09/09/2024 │
│ 3    ┆ Note préfet Renouvellement LL.… ┆ 18/11/2024 │
│ 4    ┆ 4- Plan-Eau V2.pdf              ┆ 09/09/2024 │
│ 5    ┆ 3- Note préfet Renouvellement … ┆ 18/11/2024 │
└──────┴─────────────────────────────────┴────────────┘

## 9. Regroupement des doublons

Comme une même note circule d'une réunion à l'autre, sous plusieurs versions et plusieurs formats, les candidats contiennent beaucoup de quasi-doublons. Les laisser tels quels reviendrait à remplir le contexte de cinq fois le même texte. Les candidats quasi identiques sont donc regroupés : on conserve la version validée la plus récente et les autres sont signalées par la mention « aussi dans ».

Deux critères détectent ces doublons. Le premier est la similarité de Jaccard calculée sur des groupes de 5 mots. Le second est l'inclusion d'un passage dans un autre, ce qui correspond au cas d'un même texte découpé différemment selon le format (PDF ou ODT). Ce second critère n'est appliqué que si le passage est assez long, afin qu'un simple bloc d'adresse, présent dans de nombreux courriers, ne soit pas pris pour un doublon. Sur le corpus, ce double critère détecte 67 % de doublons de plus que Jaccard seul.

La sortie liste les groupes formés et, pour chacun, la version retenue.

In [11]:
from rag_pipeline import retrieve

candidats = retrieve(retriever, requete_hyde, question)
regroupes = corpus.collapse_duplicates(candidats)
print(f"{len(candidats)} candidats -> {len(regroupes)} après regroupement des doublons")
pl.DataFrame([{"fichier retenu": Path(d.metadata["source"]).name[:50],
               "statut": "validée" if d.metadata.get("validated") else "travail",
               "aussi dans": (d.metadata.get("aussi_dans") or "")[:80]}
              for d in regroupes if d.metadata.get("aussi_dans")][:6])

30 candidats -> 26 après regroupement des doublons

shape: (4, 3)
┌─────────────────────────────────┬─────────┬─────────────────────────────────┐
│ fichier retenu                  ┆ statut  ┆ aussi dans                      │
│ ---                             ┆ ---     ┆ ---                             │
│ str                             ┆ str     ┆ str                             │
╞═════════════════════════════════╪═════════╪═════════════════════════════════╡
│ 6- note effectifs préfet aout … ┆ travail ┆ note effectifs préfet sept 24 … │
│ 2. 2405_orga_conf_territoriale… ┆ validée ┆ 2405_Note_prefet_orga_conf_ter… │
│ 231229_Note_Préfet_ZAENR_V2.od… ┆ travail ┆ 231229_Note_Préfet_ZAENR_V2.pd… │
│ Note_prefet_transition_ecologi… ┆ travail ┆ Note_prefet_transition_ecologi… │
└─────────────────────────────────┴─────────┴─────────────────────────────────┘

## 10. Rerank et sélection

Le modèle de rerank d'Albert lit chaque candidat avec la question et lui attribue une note de 0 à 1. Contrairement aux scores de la recherche, ces notes sont très contrastées : un passage pertinent obtient entre 0,4 et 0,99, un passage hors sujet reste proche de 0. Les passages sous le score minimum (0,01) sont écartés. Si aucun ne franchit ce seuil, l'assistant répond qu'il n'a rien trouvé, plutôt que d'inventer une réponse à partir de documents sans rapport.

Parmi les passages restants, on applique ensuite la limite de 2 passages par document, de façon à diversifier les sources, puis on retient 5 passages au total.

Le graphique en barres représente les scores des candidats, avec une ligne rouge au niveau du seuil. Dans la sortie réelle, 13 passages dépassent ce seuil et 5 sont retenus. Un écart net entre les barres hautes et les barres basses indique que le tri est franc.

In [12]:
from rag_pipeline import rerank_documents, filter_relevant

tries = rerank_documents(question, regroupes, top_k=len(regroupes))
scores = pl.DataFrame([{"rang": i + 1, "score": d.metadata["rerank_score"],
                        "fichier": Path(d.metadata["source"]).name[:40]} for i, d in enumerate(tries[:15])])
barres = alt.Chart(scores).mark_bar().encode(
    x=alt.X("rang:O", title="Rang après rerank"), y=alt.Y("score:Q", title="Score de pertinence"),
    tooltip=["fichier", "score"])
seuil = alt.Chart(pl.DataFrame({"seuil": [config.RERANK_MIN_SCORE]})).mark_rule(
    color="red", strokeDash=[4, 4]).encode(y="seuil:Q")
(barres + seuil).properties(width=600, height=220, title="Scores du rerank (ligne rouge : score minimum)")

alt.LayerChart(...)

In [13]:
retenus = corpus.cap_per_document(filter_relevant(tries))[: config.RAG_TOP_K_DOCS]
print(len(filter_relevant(tries)), "passages au-dessus du seuil ;", len(retenus), "retenus après plafond par document")
apercu(retenus)

11 passages au-dessus du seuil ; 5 retenus après plafond par document

shape: (5, 3)
┌──────┬─────────────────────────────────┬────────────┐
│ rang ┆ fichier                         ┆ réunion    │
│ ---  ┆ ---                             ┆ ---        │
│ i64  ┆ str                             ┆ str        │
╞══════╪═════════════════════════════════╪════════════╡
│ 1    ┆ 240619_Note_Préfet_ZAENR.odt    ┆ 24/06/2024 │
│ 2    ┆ 2. 2405_orga_conf_territoriale… ┆ 24/06/2024 │
│ 3    ┆ ppt zaenr.pdf                   ┆ 09/09/2024 │
│ 4    ┆ Note_prefet_transition_ecologi… ┆ 24/06/2024 │
│ 5    ┆ 2. transition_ecologique2024.p… ┆ 24/06/2024 │
└──────┴─────────────────────────────────┴────────────┘

## 11. Construction du contexte

Un passage de 2 000 caractères commence ou s'arrête parfois au milieu d'un raisonnement. Chaque passage retenu est donc élargi à ses voisins immédiats dans le document, un de chaque côté selon le réglage actuel. Le chevauchement est fusionné au passage, de sorte que le texte commun n'apparaisse qu'une seule fois.

Les passages ainsi élargis sont numérotés de [1] à [5] et accompagnés de leur source, de la date de réunion et de leur statut. Le modèle reçoit pour consigne de citer ces numéros dans sa réponse, ce qui permet ensuite de vérifier chaque affirmation dans le document correspondant.

La sortie compare les longueurs avant et après élargissement. Elles passent de 1 500 à 1 900 caractères pour les passages seuls à 2 000 à 5 000 caractères une fois les voisins ajoutés. Le contexte transmis au modèle reste donc de taille raisonnable, tout en offrant assez de matière pour répondre.

In [14]:
from rag_pipeline import expand_with_neighbors, format_context

textes = expand_with_neighbors(retenus, retriever)
print("Longueur des passages : seuls", [len(corpus.chunk_body(d)) for d in retenus],
      "| élargis", [len(t) for t in textes])
contexte = format_context(retenus, textes)
print(contexte[:1200], "...")

Longueur des passages : seuls [1785, 1919, 1481, 1901, 1549] | élargis [2078, 3872, 3285, 4017, 5062]
[1] 240619_Note_Préfet_ZAENR.odt | réunion du 24/06/2024 | version de travail
Direction Départementale
des Territoires et de la Mer

Service de l’Environnement
Affaire suivie par :  Alexis DRAPIER
03 21 22 98 11/alexis.drapier@pas-de-calais.gouv.fr
Service de l’Animation et de l’Appui Territorial
Affaire suivie par : Hélène VILLAR
Helene.villar@pas-de-calais.gouv.fr

Arras, le
Note à l’attention de Monsieur le Préfet
OBJET : Évolutions du contexte d’organisation de la conférence territoriale prévue par loi APER dans le cadre des récentes annonces présidentielles

PJ : Note portant sur les modalités d’organisation de la conférence territoriale prévue par loi APER

Conformément aux dispositions de la loi APER, le référent préfectoral doit désormais arrêter la cartographie des zones d'accélération identifiées qu’il devra transmettre au comité régional de l'énergie (CRÉ). En parallèle, il devra consulter, au sein d'une conférence territoriale, les établissements publics mentionnés à l'article L. 143-16 du code de l'urbanisme et les établissements publics de coopération intercommunale.
Le calendrier discuté en CAR et figurant dans le courrier d ...

## 12. Génération de la réponse

La fonction `rag_query` enchaîne toutes les étapes précédentes : reformulation, HyDE, recherche hybride, regroupement des doublons, rerank, construction du contexte, puis appel au modèle de réponse. Celui-ci rédige à partir des seuls passages fournis et cite les numéros [1], [2] et suivants.

La cellule affiche la réponse, puis un tableau des sources dont les numéros correspondent à ceux des citations. Chaque ligne indique le document, la date de réunion, le statut et le score de rerank. En lisant ce tableau, on peut juger la fiabilité de la réponse : une source validée et bien notée a plus de poids qu'un brouillon dont le score est faible.

L'interface Streamlit présente les mêmes informations, avec en plus un aperçu de la page PDF concernée et un bouton pour ouvrir le document. Pendant le traitement, elle affiche chaque étape franchie et le temps écoulé.

In [15]:
from rag_pipeline import rag_query

resultat = rag_query(question, retriever, llm)
display(Markdown(resultat["answer"]))
pl.DataFrame([{"n°": p["num"], "source": p["label"], "réunion et statut": p["details"],
               "score": round(p["score"] or 0, 3)} for p in resultat["passages"]])

Le calendrier de la conférence territoriale prévue par la loi APER a évolué suite aux annonces de dissolution de l'Assemblée nationale. Voici les étapes clés, conformément aux documents fournis :

1. **Préparation des synthèses** :
   - Du 01.05.2024 au 05.09.2024 : Les synthèses des Directions Départementales des Territoires et de la Mer (DDTM) et des Directions Régionales de l'Environnement, de l'Aménagement et du Logement (DREAL) sont préparées en vue des conférences territoriales [1].

2. **Conferences territoriales et synthèses départementales** :
   - Du 10.06.2024 au 30.06.2024 : Les conférences territoriales et les synthèses départementales sont réalisées [2].

3. **Transmission de la cartographie départementale** :
   - Au 06.09.2024 : Les référents préfectoraux transmettent la cartographie départementale au Comité Régional de l'Énergie (CRÉ) [1].

4. **Synthèse des cartographies et convocation du CRÉ** :
   - Dernier trimestre 2024 : Les services de l'État réalisent la synthèse des cartographies proposées et envoient les éléments préparatoires aux membres du CRÉ pour une convocation puis un arrêt de la cartographie, probablement fin 2024 [1].

Il est important de noter que le département du Pas-de-Calais a fait le choix d'une consultation électronique pour l'organisation de la conférence territoriale, contrairement à d'autres départements qui pourraient opter pour des réunions en présentiel [1][2].

Pour plus de détails sur les modalités d'organisation et les acteurs impliqués, vous pouvez consulter les documents de référence [1][2][3][4][5].

shape: (5, 4)
┌─────┬─────────────────────────────────┬─────────────────────────────────┬───────┐
│ n°  ┆ source                          ┆ réunion et statut               ┆ score │
│ --- ┆ ---                             ┆ ---                             ┆ ---   │
│ i64 ┆ str                             ┆ str                             ┆ f64   │
╞═════╪═════════════════════════════════╪═════════════════════════════════╪═══════╡
│ 1   ┆ 240619_Note_Préfet_ZAENR.odt    ┆ réunion du 24/06/2024 | versio… ┆ 0.994 │
│ 2   ┆ 2. 2405_orga_conf_territoriale… ┆ réunion du 24/06/2024 | versio… ┆ 0.989 │
│ 3   ┆ ppt zaenr.pdf, p. 3             ┆ réunion du 09/09/2024 | versio… ┆ 0.972 │
│ 4   ┆ Note_prefet_transition_ecologi… ┆ réunion du 24/06/2024 | versio… ┆ 0.926 │
│ 5   ┆ 2. transition_ecologique2024.p… ┆ réunion du 24/06/2024 | versio… ┆ 0.637 │
└─────┴─────────────────────────────────┴─────────────────────────────────┴───────┘

## 13. Évaluation

Modifier un réglage améliore parfois une réponse et en dégrade une autre. Pour mesurer l'effet réel d'un changement, le projet dispose d'un jeu de 55 questions de référence, stocké dans `evaluation/questions.yaml`. Il comprend 49 questions dont la réponse figure dans un document connu (chiffres précis, références exactes, questions de fond, contenus issus de l'OCR, un courriel) et 6 questions hors sujet, pour lesquelles la bonne réponse est « rien de pertinent ».

Le script `evaluate.py` compare des variantes du pipeline et la cellule en affiche le tableau : succès, questions hors sujet rejetées, MRR, doublons par réponse et durée en secondes. La configuration de référence trouve la bonne source pour les 49 questions documentées et rejette les 6 questions hors sujet. Sans recherche hybride, le succès tombe à 18 %. Sans rerank, aucune question hors sujet n'est rejetée et le MRR passe de 0,97 à 0,48. Sans dédoublonnage, chaque réponse contient en moyenne un doublon. HyDE multiplie la durée par environ 40 sans gain, d'où sa désactivation.

Ces résultats doivent être lus avec prudence : les questions ont été rédigées avec le vocabulaire des documents, ce qui avantage la recherche par mots exacts. Le détail figure dans `evaluation/rapport_evaluation.md`.

In [16]:
import csv
import re

resultats = []
for fichier in sorted(glob.glob("evaluation/resultats/*.csv")):
    # Nom : <date>_<réglages>_seuil<x>_<libellé>.csv
    libelle = re.search(r"_seuil[\d.]+_(.+)$", Path(fichier).stem)
    with open(fichier, encoding="utf-8-sig") as f:
        lignes = list(csv.DictReader(f, delimiter=";"))
    documentees = [l for l in lignes if l["sources_attendues"] != "(aucune)"]
    hors_sujet = [l for l in lignes if l["sources_attendues"] == "(aucune)"]
    resultats.append({
        "variante": libelle.group(1) if libelle else Path(fichier).stem,
        "succès": round(sum(l["succes"] == "True" for l in documentees) / len(documentees), 2),
        "hors sujet rejetés": round(sum(l["succes"] == "True" for l in hors_sujet) / max(len(hors_sujet), 1), 2),
        "MRR": round(sum(1 / int(l["rang_final"]) for l in documentees if l["rang_final"]) / len(documentees), 2),
        "doublons par réponse": round(sum(int(l["doublons"]) for l in lignes) / len(lignes), 2),
        "durée (s)": round(sum(float(l["duree_s"]) for l in lignes) / len(lignes), 1),
    })
pl.Config.set_tbl_rows(20)
pl.DataFrame(resultats)

shape: (10, 6)
┌──────────────────────────┬────────┬────────────────────┬──────┬──────────────────────┬───────────┐
│ variante                 ┆ succès ┆ hors sujet rejetés ┆ MRR  ┆ doublons par réponse ┆ durée (s) │
│ ---                      ┆ ---    ┆ ---                ┆ ---  ┆ ---                  ┆ ---       │
│ str                      ┆ f64    ┆ f64                ┆ f64  ┆ f64                  ┆ f64       │
╞══════════════════════════╪════════╪════════════════════╪══════╪══════════════════════╪═══════════╡
│ reference                ┆ 1.0    ┆ 1.0                ┆ 0.97 ┆ 0.0                  ┆ 0.4       │
│ sans_dedoublonnage       ┆ 1.0    ┆ 1.0                ┆ 0.96 ┆ 1.05                 ┆ 0.3       │
│ sans_plafond             ┆ 1.0    ┆ 1.0                ┆ 0.97 ┆ 0.0                  ┆ 0.4       │
│ sans_hybride             ┆ 0.18   ┆ 1.0                ┆ 0.18 ┆ 0.0                  ┆ 0.4       │
│ sans_rerank              ┆ 0.92   ┆ 0.0                ┆ 0.48 ┆ 0.0                  ┆ 0.1       │
│ dedoublonnage_jaccard_se ┆ 1.0    ┆ 1.0                ┆ 0.98 ┆ 0.38                 ┆ 0.4       │
│ ul                       ┆        ┆                    ┆      ┆                      ┆           │
│ sans_entete_vectoriel    ┆ 0.29   ┆ 1.0                ┆ 0.27 ┆ 0.0                  ┆ 0.3       │
│ sans_entete              ┆ 1.0    ┆ 1.0                ┆ 0.93 ┆ 0.0                  ┆ 0.3       │
│ reference_reponses       ┆ 1.0    ┆ 1.0                ┆ 0.97 ┆ 0.0                  ┆ 0.4       │
│ avec_hyde                ┆ 1.0    ┆ 1.0                ┆ 0.98 ┆ 0.0                  ┆ 15.1      │
└──────────────────────────┴────────┴────────────────────┴──────┴──────────────────────┴───────────┘

## Pour aller plus loin

La chaîne complète se résume ainsi. Les fichiers sont lus, passés si besoin par l'OCR, puis découpés en passages munis d'un en-tête contextuel et indexés de deux manières, par le sens et par les mots exacts. Une question est ensuite reformulée si elle dépend de l'échange précédent, enrichie d'une réponse hypothétique pour la recherche vectorielle, puis soumise aux deux index dont les classements sont fusionnés. Les doublons sont regroupés, le rerank trie les candidats et écarte les passages sans rapport, le contexte est élargi aux voisins, et le modèle rédige une réponse qui cite ses sources.

Pour agir sur le comportement de l'assistant, deux points d'entrée suffisent. Le fichier `parametres.yaml` regroupe les réglages et les prompts. Le script `evaluate.py` permet de vérifier, sur les 55 questions de référence, l'effet d'une modification avant de l'adopter.

Plusieurs limites doivent rester à l'esprit. La qualité de l'OCR est à vérifier sur les documents qui comptent. HyDE et la génération ne sont pas déterministes, si bien que deux exécutions peuvent différer. Enfin, les seuils (score minimum, critères de doublons) ont été calibrés sur ce corpus et devront être réexaminés si les documents changent de nature.